resolver: nightly-2020-06-29 # GHC 8.10.1

packages:
- .

extra-deps:
- pandoc-2.10
- hslua-1.1.2@sha256:6c231b2af447430d1ed04f065d40bb6882ece93cc7f32f4051dc99deb69beeae,9694
- jira-wiki-markup-1.3.2@sha256:b5f0901208a0ee07aff60f5356aeb851b7aa7950c75a18a15fd34247a35886d8,3819
- git: https://github.com/LaurentRDC/pandoc-include-code.git
  commit: 162ae92edc80601bde8450bf933c0127e8c2b53a
  
# Faster compilation.
# See here: 
#   https://downloads.haskell.org/ghc/latest/docs/html/users_guide/flags.html#miscellaneous-compiler-options
# and here:
#   https://ghc.gitlab.haskell.org/ghc/doc/users_guide/runtime_control.html
# ghc-options:
#   pandoc: -j "+RTS -A64m -RTS"
#   pandoc-citeproc: -j "+RTS -A64m -RTS"
#   $targets: -j "+RTS -A64m -RTS"
