resolver: nightly-2021-07-04

packages:
- .

extra-deps:
- pandoc-2.14.0.3
- network-3.1.0.0

# For development
- git: https://github.com/owickstrom/pandoc-include-code.git
  commit: 89c8465549960872257da993a399d978a269d6a6
