resolver: lts-17.5 # GHC 8.10.4

packages:
- .

extra-deps:
- pandoc-2.12
- hslua-module-path-0.1.0.1

# For development
- git: https://github.com/owickstrom/pandoc-include-code.git
  commit: 89c8465549960872257da993a399d978a269d6a6
