jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-lts-14:
        ARGS: "--resolver lts-14"
    maxParallel: 6
  steps:
    # Note that the task to add conda to PATH must be done
    # in its own step for `source activate ...` command to work.
    # I suspect that the environment variable need to be
    # updated/refreshed, which is done at the beginning of a
    # step
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH.
    
  - bash: |
      # Create anaconda environment
      conda create --quiet --yes --name testenv python=3.7

      source activate testenv

      # Pillow is required to save images to jpg
      conda install --quiet --yes matplotlib pillow

      # Plotly installation instructions are more complex because we export static images
      # https://plot.ly/python/static-image-export/
      conda install --quiet --yes -c plotly plotly-orca psutil requests
      conda install --quiet --yes plotly

      conda list
    displayName: Install Matplotlib & Plotly/Python toolkits

  - bash: |
      sudo apt-get --quiet --yes install octave
    displayName: Install GNU Octave toolkit

  - bash: |
      sudo apt-get --quiet --yes install r-cran-littler
    displayName: Install R toolchain

  - bash: |
      sudo Rscript -e "install.packages('ggplot2', repos='http://cran.rstudio.com/')"
    displayName: Install ggplot2

  - bash: |
      sudo apt-get --quiet --yes install gnuplot
    displayName: Install gnuplot

  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      mkdir -p ~/.local/bin
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      
      export PATH=$HOME/.local/bin:$PATH
      
      stack --install-ghc $ARGS test --bench --only-dependencies

      source activate testenv
      stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}}'

  - bash: |
      stack install pandoc-plot --local-bin-path $(System.DefaultWorkingDirectory)
    displayName: Build artifact executable
      
  - publish: $(System.DefaultWorkingDirectory)/pandoc-plot
    artifact: pandoc-plot
