jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-lts-14:
        ARGS: "--resolver lts-14"
    maxParallel: 6
  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - bash: |
      # Create anaconda environment
      conda create --quiet --yes --name testenv python=3.7

      conda activate testenv

      # Pillow is required to save images to jpg
      conda install --quiet --yes matplotlib pillow

      # Plotly installation instructions are more complex because we export static images
      # https://plot.ly/python/static-image-export/
      conda install --quiet --yes -c plotly plotly-orca psutil requests
      conda install --quiet --yes plotly

      conda list
    displayName: Install Matplotlib & Plotly/Python toolkits

  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
            
      stack --install-ghc $ARGS test --bench --only-dependencies

      conda activate testenv
      stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
