jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 120
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        stable:
          ARGS: "--stack-yaml stack.yaml"
      maxParallel: 6
  
    steps:
    # Caching steps are inspired from haskell-ide-engine
    # https://github.com/digital-asset/ghcide/blob/master/.azure/linux-stack.yml
    - task: Cache@2
      inputs:
        key: stack-v2 | $(Agent.OS) | $(Build.SourcesDirectory)/stack.yaml | $(Build.SourcesDirectory)/pandoc-plot.cabal
        path: .azure-cache
        cacheHitVar: CACHE_RESTORED
      displayName: "Cache stack-root"
  
    - bash: |
        mkdir -p ~/.stack
        tar xzf .azure-cache/stack-root.tar.gz -C $HOME
      displayName: "Unpack cache"
      condition: eq(variables.CACHE_RESTORED, 'true')
  
    - bash: |
        brew update
        brew install haskell-stack 
      displayName: Install stack
  
    - bash: |
        export PATH=$HOME/.local/bin:$PATH
        stack setup $ARGS
      displayName: Install GHC
  
    - bash: |
        export PATH=$HOME/.local/bin:$PATH
        stack build $ARGS --only-dependencies
      displayName: Build dependencies
  
    - bash: |
        export PATH=$HOME/.local/bin:$PATH
        stack build $ARGS
      displayName: Build `pandoc-plot`
  
    - bash: |
        export PATH=$HOME/.local/bin:$PATH
        mkdir .azure-deploy
        stack install $ARGS --local-bin-path .azure-deploy
        cd .azure-deploy
        ARTIFACT_NAME=pandoc-plot-macos-x86_64
        tar -vcJf $(Build.ArtifactStagingDirectory)/$ARTIFACT_NAME.tar.xz *
      displayName: Install `pandoc-plot`
  
    - bash: |
        export PATH=$HOME/.local/bin:$PATH
        stack build $ARGS --test --bench --only-dependencies
      displayName: Build Test-dependencies
  
      # Note that the task to add conda to PATH must be done
      # in its own step for `source activate ...` command to work.
      # I suspect that the environment variable need to be
      # updated/refreshed, which is done at the beginning of a
      # step
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH.

      # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
      # We need to take ownership if we want to update conda or install packages globally
    - bash: sudo chown -R $USER $CONDA
      displayName: Take ownership of conda installation
      
    - bash: |
        conda create --quiet --yes --name testenv python=3.7
      displayName: Create Python test environment
        
      # Note that Pillow is required to save images to jpg
      # Plotly installation instructions are more complex because we export static images
      # https://plot.ly/python/static-image-export/
    - bash: |
        source activate testenv
        conda install --quiet --yes matplotlib pillow
      displayName: Install Matplotlib toolkit

    - bash: |
        source activate testenv
        conda install --quiet --yes -c plotly plotly-orca psutil requests
        conda install --quiet --yes plotly
      displayName: Install Plotly/Python toolkit

    - bash: |
        source activate testenv
        conda install --quiet --yes -c conda-forge bokeh selenium geckodriver firefox
      displayName: Install Python/Bokeh toolkit
  
    - bash: |
        export PATH=$HOME/.local/bin:$PATH
        source activate testenv
        stack test $ARGS
      displayName: "Unit tests"

    - bash: |
        stack exec -- pandoc-plot --manual
      displayName: "Testing manual"

    - bash: |
        stack install pandoc
        stack install
        source activate testenv
        stack exec -- pandoc --filter pandoc-plot -i tests/integration.md -t html
        stack exec -- pandoc-plot clean tests/integration.md
        echo "Logging output:"
        echo $(cat log.txt)
      displayName: "Integration tests"
  
    - publish: $(Build.ArtifactStagingDirectory)/pandoc-plot-macos-x86_64.tar.xz
      artifact: pandoc-plot-macos-x86_64.tar.xz

    - bash: |
        mkdir -p .azure-cache
        tar czf .azure-cache/stack-root.tar.gz -C $HOME .stack
      displayName: "Pack cache"
  
