jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 120
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        stable:
          ARGS: "--stack-yaml stack.yaml"
      maxParallel: 6
  
    steps:
    # Caching steps are inspired from haskell-ide-engine
    # https://github.com/digital-asset/ghcide/blob/master/.azure/linux-stack.yml
    - task: Cache@2
      inputs:
        key: stack | $(Agent.OS) | $(Build.SourcesDirectory)/stack.yaml | $(Build.SourcesDirectory)/pandoc-plot.cabal
        path: .azure-cache
        cacheHitVar: CACHE_RESTORED
      displayName: "Cache stack-root"
  
    - bash: |
        mkdir -p ~/.stack
        tar xzf .azure-cache/stack-root.tar.gz -C $HOME
      displayName: "Unpack cache"
      condition: eq(variables.CACHE_RESTORED, 'true')
  
    - bash: |
        mkdir -p ~/.local/bin
        curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | \
          tar vxz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      displayName: Install stack
  
    - bash: |
        stack setup $ARGS
      displayName: Install GHC
  
    - bash: |
        stack build $ARGS --only-dependencies
      displayName: Build dependencies
  
    - bash: |
        stack build $ARGS
      displayName: Build `pandoc-plot`

    - bash: |
        mkdir .azure-deploy-static
        stack install $ARGS --flag pandoc-plot:static --local-bin-path .azure-deploy-static
        cd .azure-deploy-static
        upx --best pandoc-plot
        $VERSION = $(stack exec -- pandoc-plot --version)
        ARTIFACT_NAME=pandoc-plot-$(VERSION)-linux-x86_64-static
        tar -vcJf $(Build.ArtifactStagingDirectory)/$ARTIFACT_NAME.tar.xz *
      displayName: Create static `pandoc-plot` artifact
  
    - bash: |
        mkdir .azure-deploy
        stack install $ARGS --local-bin-path .azure-deploy
        cd .azure-deploy
        upx --best pandoc-plot
        $VERSION = $(stack exec -- pandoc-plot --version)
        ARTIFACT_NAME=pandoc-plot-$(VERSION)-linux-x86_64
        tar -vcJf $(Build.ArtifactStagingDirectory)/$ARTIFACT_NAME.tar.xz *
      displayName: Install `pandoc-plot`
  
    - bash: |
        stack build $ARGS --test --bench --only-dependencies
      displayName: Build Test-dependencies
  
      # Note that the task to add conda to PATH must be done
      # in its own step for `source activate ...` command to work.
      # I suspect that the environment variable need to be
      # updated/refreshed, which is done at the beginning of a
      # step
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH.
      
    - bash: |
        conda create --quiet --yes --name testenv python=3.7
      displayName: Create Python test environment
        
      # Note that Pillow is required to save images to jpg
      # Plotly installation instructions are more complex because we export static images
      # https://plot.ly/python/static-image-export/
    - bash: |
        source activate testenv
        conda install --quiet --yes matplotlib pillow
      displayName: Install Matplotlib toolkit

    - bash: |
        source activate testenv
        conda install --quiet --yes -c plotly plotly-orca psutil requests
        conda install --quiet --yes plotly
      displayName: Install Plotly/Python toolkit

    - bash: |
        source activate testenv
        conda install --quiet --yes -c conda-forge bokeh selenium geckodriver firefox
      displayName: Install Python/Bokeh toolkit

    - bash: |
        sudo apt-get update
      displayName: Update apt-get archive
  
    - bash: |
        sudo apt-get --quiet --yes install octave
      displayName: Install GNU Octave toolkit
    
    - bash: |
        sudo apt --quiet --yes install graphviz
      displayName: Install Graphviz toolkit
  
    - bash: |
        sudo apt-get --quiet --yes install r-cran-littler
      displayName: Install R toolchain
  
    - bash: |
        sudo Rscript -e "install.packages('plotly', repos='http://cran.rstudio.com/')"
      displayName: Install Plotly/R toolkit
      
    - bash: |
        sudo Rscript -e "install.packages('ggplot2', repos='http://cran.rstudio.com/')"
      displayName: Install ggplot2
    
    - bash: |
        sudo Rscript -e "install.packages('plotly')"
      displayName: Install Plotly/R toolkit
  
    - bash: |
        sudo apt-get --quiet --yes install gnuplot
      displayName: Install gnuplot
    
    - bash: |
        sudo apt --quiet --yes install julia
        julia -e 'using Pkg; Pkg.add("Plots");'
      displayName: Install Julia/Plots.jl
  
    - bash: |
        source activate testenv
        stack test $ARGS
      displayName: "Unit tests"

    - bash: |
        stack install pandoc
        stack install
        source activate testenv
        stack exec -- pandoc --filter pandoc-plot -i tests/integration.md -t html
        stack exec -- pandoc-plot clean tests/integration.md
      displayName: "Integration tests"
  
    - publish: $(Build.ArtifactStagingDirectory)/pandoc-plot-linux-x86_64.tar.xz
      artifact: pandoc-plot-linux-x86_64.tar.xz

    - bash: |
        mkdir -p .azure-cache
        tar czf .azure-cache/stack-root.tar.gz -C $HOME .stack
      displayName: "Pack cache"
  
