jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-lts-14:
        ARGS: "--resolver lts-14"
    maxParallel: 6
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --quiet --yes --name testenv python=3.7
    displayName: Create Anaconda environment

  - bash: |
      source activate testenv

      # Pillow is required to save images to jpg
      conda install --quiet --yes matplotlib pillow

      # Plotly installation instructions are more complex because we export static images
      # https://plot.ly/python/static-image-export/
      conda install --quiet --yes -c plotly plotly-orca psutil requests
      conda install --quiet --yes plotly
    displayName: Install Python dependencies to test Matplotlib & Plotly/Python toolkits

  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      mkdir -p ~/.local/bin
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      
      export PATH=$HOME/.local/bin:$PATH
      
      stack --install-ghc $ARGS test --bench --only-dependencies

      source activate testenv
      conda env list
      stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
