
directory: plots
source: true
caption_format: markdown+tex_math_dollars
format: PNG
strict: true

matplotlib:
  executable: python
  transparent: true

bokeh:
  executable: python

logging:
  verbosity: info