# This Github Actions workflow is modified from
# https://kodimensional.dev/github-actions
name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    
    if: contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: pandoc-plot tests - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - name: Setup Haskell toolchain
      uses: actions/setup-haskell@v1
      with:
        enable-stack: true
        stack-version: 'latest'

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - uses: actions/cache@v2
      name: Cache Haskell build artifacts
      with:
        path: ~/.stack
        key: ${{ runner.os }}-v2-${{ hashFiles('stack.yaml.lock') }}

    - uses: actions/cache@v2
      name: Cache Python build artifacts
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('.github/workflows/requirements.txt') }}

    - name: Install Python toolkits
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r .github/workflows/requirements.txt

    - name: Build
      run: |
        stack build --stack-yaml stack.yaml --test --no-run-tests

    - name: Test
      run: |
        stack test --stack-yaml stack.yaml 
    
    - name: Build artifact
      run: |
        mkdir dist
        stack install --stack-yaml stack.yaml --flag pandoc-plot:static --local-bin-path dist
        cd dist
        upx --best pandoc-plot

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: dist/pandoc-plot
        name: 'pandoc-plot-${{matrix.os}}-x86_64'