# This Github Actions workflow is modified from
# https://kodimensional.dev/github-actions
name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    name: stack ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    # https://github.com/actions/setup-haskell
    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      with:
        stack-version: "latest"
        enable-stack: true
        stack-no-global: true
    
    # https://github.com/actions/cache
    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}

    - name: Build
      run: |
        stack build --stack-yaml stack.yaml --test --no-run-tests

    - name: Test
      run: |
        stack test --stack-yaml stack.yaml 