name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-test:
    if: contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Haskell toolchain
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        stack-version: 'latest'

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - uses: r-lib/actions/setup-r@v1

    - uses: actions/cache@v2
      name: Cache Haskell build artifacts
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}

    - uses: actions/cache@v2
      name: Cache Python build artifacts
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('.github/workflows/requirements.txt') }}

    - name: Build pandoc-plot
      run: stack install

    - name: Install Python toolkits
      run: |
        python -m pip install --upgrade pip
        pip install numpy wheel
        pip install -r .github/workflows/requirements.txt
    
    - name: Install Plots.jl toolkit
      shell: julia {0}
      run: |
        using Pkg
        Pkg.add("Plots")

    - name: Install GGPlot2
      run: |
        Rscript -e "install.packages('ggplot2', repos='http://cran.rstudio.com/')"
        Rscript -e 'if(!require("ggplot2")) {quit(status=1)}'"

    - name: Install Octave, Gnuplot, Graphviz [Linux]
      if: runner.os == 'Linux'
      run: |
        sudo apt-get --quiet --yes install octave
        sudo apt-get --quiet --yes install gnuplot
        sudo apt-get --quiet --yes install graphviz

    - name: Install Graphviz [Windows]
      if: runner.os == 'Windows'
      shell: pwsh
      run: |        
        choco install --yes --no-progress graphviz
        dot -c

    - name: Check installed plotting toolkits
      run: |
        stack install
        stack exec -- pandoc-plot toolkits

    - name: Unit tests
      run: stack test
    
    - name: Integration tests
      run: |
        stack install pandoc
        stack install
        stack exec -- pandoc --filter pandoc-plot -i tests/integration.md -t html
        stack exec -- pandoc --filter pandoc-plot -i tests/issue16.md -t native
        echo "Logging output:"
        echo "$(cat log.txt)"

        stack exec -- pandoc-plot clean tests/integration.md
        stack exec -- pandoc-plot clean tests/issue16.md
    
    - name: Build documentation
      shell: pwsh
      run: .\tools\mkmanual.ps1

    - name: Build artifact
      run: |
        mkdir artifact
        stack install --local-bin-path artifact
    
    - name: Build artifact [Linux - static]
      if: runner.os == 'Linux'
      run: |
        mkdir artifact-static
        stack install --flag pandoc-plot:static --local-bin-path artifact-static

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pandoc-plot-${{ runner.os }}-x86_64
        path: artifact/pandoc-plot

    - name: Upload artifact [Linux - static]
      uses: actions/upload-artifact@v2
      with:
        name: pandoc-plot-${{ runner.os }}-x86_64-static
        path: artifact-static/pandoc-plot

    - name: Build Installer [Windows]
      if: runner.os == 'Windows'
      shell: pwsh
      run: .\tools\build-setup.ps1

    - name: Upload artifact [Windows - installer]
      uses: actions/upload-artifact@v2
      if: runner.os == 'Windows'
      with:
        name: pandoc-plot-${{ runner.os }}-x86_64
        path: installer/pandoc-plot-wininst-x86_64.exe